version: "3"

services:

  l1_chain:
    image: omgx/hardhat:latest
    ports:
      - 9545:9545

  geth_l2:
    image: omgx/go-ethereum:latest
    volumes:
      - geth:/l2-node/l2:rw
    ports:
      - 8545:8545
      - 8546:8546

  batch_submitter:
    image: omgx/batch-submitter:latest

  data_transport_layer:
    image: omgx/data-transport-layer:latest
    ports:
      - 7878:7878

  deployer:
    image: omgx/deployer:latest
    ports:
      - 8080:8080

  message_relayer:
    image: omgx/message-relayer:latest

  verifier:
    image: omgx/go-ethereum:latest
    volumes:
      - verifier:/root/.ethereum:rw
    ports:
      - 8045:8045
      - 8046:8046

  fraud_prover:
    image: omgx/fraud-prover:latest

volumes:

  geth:

  verifier: