apiVersion: v2
name: cert-manager
description: OMG's cert-manager installation for vault
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.3

dependencies:
- name: cert-manager
  version: v1.1.0
  repository: https://charts.jetstack.io
