---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-certificate
spec:
  secretName: vault-internal-certificate
  duration: 2160h # 90d
  subject:
    countries:
      - TH
    localities:
      - Bangkok
    organizations:
      - OMG Network
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "vault-internal.default.svc.cluster.local"
    - "*.vault-internal.default.svc.cluster.local"
  ipAddresses:
    - "127.0.0.1"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
