---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-audit
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
