version: "3"

services:
  
# base service builder

  omgx_builder:
    image: omgx/omgx_builder
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.omgx_monorepo

# deploys OMGX contracts and serves contract addresses 

  omgx_deployer:
    depends_on:
      - l1_chain
      - deployer
      - l2geth
    image: omgx/omgx_deployer
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.omgx_deployer
    environment:
        TEST: 1 #controls whther the test ERC20 is deployed, too
        NO_COMPILE: 0 #sorry for the flipped logic. NO_COMPILE 0 probably means `please compile`
        L1_NODE_WEB3_URL: http://l1_chain:8545
        L2_NODE_WEB3_URL: http://l2geth:8545
        URL: http://deployer:8081/addresses.json
        # DO NOT use in production
        DEPLOYER_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        RETRIES: 70
    ports:
        # expose the service to the host for getting the contract addrs
      - ${OMGX_DEPLOYER_PORT:-8078}:8079

# serves data needed for the main message-relayer not to double-relay, saving gas
# this assumes the deployer has come up correctly, and has deployed the right contracts

  omgx_bl-wl:
    depends_on:
      - l1_chain
      - deployer
      - omgx_deployer
      - l2geth
    image: omgx/omgx_bl-wl
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.omgx_bl-wl
    environment:
        OMGX_URL: http://omgx_deployer:8079/addresses.json
        BL_WL_PORT: 9000
        RETRIES: 70
    ports:
      - 9000:9000

# a second relay system for messages that need to get to L1 quickly
# NOTE - all withdrawal messenges use the standard relayer with its 7 day window

  omgx_message-relayer-fast:
    depends_on:
      - l1_chain
      - deployer
      - omgx_deployer
      - l2geth
      - omgx_bl-wl
    image: omgx/omgx_message-relayer-fast
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.omgx_message-relayer-fast
    environment:
        L1_NODE_WEB3_URL: http://l1_chain:8545
        L2_NODE_WEB3_URL: http://l2geth:8545
        # This is who pays for the fast message relayer
        L1_WALLET_KEY: "0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0"
        URL: http://deployer:8081/addresses.json
        OMGX_URL: http://omgx_deployer:8079/addresses.json
        POLLING_INTERVAL: 1500
        GET_LOGS_INTERVAL: 500
        WHITELIST_ENDPOINT: http://bl-wl:9000/whitelist.json
        RETRIES: 70

# and, tests for all the OMGX-specific services

  omgx_integration_tests:
    image: omgx/omgx_builder
    deploy:
       replicas: 0
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.omgx_monorepo
    entrypoint:
        - "/bin/sh"
        - -ecx
        - |
            cd /optimism/packages/omgx/contracts
            yarn test:integration
    environment:
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      URL: http://deployer:8081/addresses.json
      OMGX_URL: http://omgx_deployer:8079/addresses.json
